spring:
  datasource:
      url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: passwd
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    show-sql: true


