spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/mydb
    username: <db user>
    password: <db passwd>
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql : true
    properties:
      hibernate:
        database: mariadb
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

