spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/mydb
    username: <mention this>
    password: <mention this>
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql : true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

