spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/mydb
    username: sharath
    password: sharathchandra
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql : true
    properties:
      hibernate:
        database: mariadb
        format_sql: true
    database-platform: org.hibernate.dialect.MariaDBDialect

